services:
  - type: web
    name: tutsin-app
    env: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: USE_DB
        value: true
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_SSL
        value: true